apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmc-nginx
spec:
  selector:
    matchlabels:
      app: app-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: con-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          targetPort: 88
